networks:
  bank-network:
    driver: bridge

services:
  agencies-mcp-server:
    build:
      context: ./agencies-mcp-server
      dockerfile: Dockerfile
    container_name: bank-agencies-mcp
    ports:
      - "8012:8012"
    env_file: ./agencies-mcp-server/.env
    networks:
      - bank-network

  transactions-api:
    build:
      context: ./transactions-api
      dockerfile: Dockerfile
    container_name: bank-transactions-api
    ports:
      - "8010:8010"
    env_file: ./transactions-api/.env
    networks:
      - bank-network

  transactions-agent-autogen:
    profiles: [autogen]
    build:
      context: ./transactions-agent
      dockerfile: autogen-agent/Dockerfile
    container_name: bank-transactions-agent
    ports:
      - "8011:8011"
    env_file: ./transactions-agent/.env
    volumes:
      - ~/podman_share/llm_config.yaml:/app/llm_config.yaml:ro,z
    networks:
      - bank-network
    depends_on:
      - transactions-api
      - agencies-mcp-server

  transactions-agent-strands:
    profiles: [strands]
    build:
      context: ./transactions-agent
      dockerfile: strands-agent/Dockerfile
    container_name: bank-transactions-agent
    ports:
      - "8011:8011"
    env_file: ./transactions-agent/.env
    volumes:
      - ~/podman_share/llm_config.yaml:/app/llm_config.yaml:ro,z
    networks:
      - bank-network
    depends_on:
      - transactions-api
      - agencies-mcp-server

  transactions-agent-langchain:
    profiles: [langchain]
    build:
      context: ./transactions-agent
      dockerfile: langchain-agent/Dockerfile
    container_name: bank-transactions-agent
    ports:
      - "8011:8011"
    env_file: ./transactions-agent/.env
    volumes:
      - ~/podman_share/llm_config.yaml:/app/llm_config.yaml:ro,z
    networks:
      - bank-network
    depends_on:
      - transactions-api
      - agencies-mcp-server
